required_packages:
# tag::required_packages[]
- firewalld
- haproxy
- httpd
# end::required_packages[]

required_services:
- haproxy
- httpd
- firewalld

firewalld_services:
- https
- http

firewalld_ports:
- 8080/tcp
- 6443/tcp
- 22623/tcp

ocp_install_root_dir: "openshift"
ocp_install_root_dir_under_user_home: true
#ocp_install_dir: "install_dir"
# 4.15.17
ocp_version: 4.15.46
ocp_release_arch: amd64
ocp_cluster_name: ocp
use_compute_nodes: false